MIPS: VPE: Remove vpe_getuid and vpe_getgid
The linux build-bot recently reported a build error in arch/mips/kernel/vpe.c

     tree:   git://git.kernel.org/pub/scm/linux/kernel/git/ebiederm/user-namespace.git for-linus
     head:   18384e57bb3034be3e9376a6697657954d926096
     commit: 18384e57bb3034be3e9376a6697657954d926096 [4/4] userns:  userns: Remove UIDGID_STRICT_TYPE_CHECKS
     config: make ARCH=mips maltaaprp_defconfig

     All error/warnings:

        arch/mips/kernel/vpe.c: In function 'vpe_open':
     >> arch/mips/kernel/vpe.c:1086:9: error: incompatible types when assigning to type 'unsigned int' from type 'kuid_t'
     >> arch/mips/kernel/vpe.c:1087:9: error: incompatible types when assigning to type 'unsigned int' from type 'kgid_t'

     vim +1086 arch/mips/kernel/vpe.c

     c1d37eb2 Jesper Juhl   2010-10-30  1080			return -ENOMEM;
     c1d37eb2 Jesper Juhl   2010-10-30  1081  		}
     01705254 Ralf Baechle  2005-07-14  1082  		v->plen = P_SIZE;
     01705254 Ralf Baechle  2005-07-14  1083  		v->load_addr = NULL;
     01705254 Ralf Baechle  2005-07-14  1084  		v->len = 0;
     01705254 Ralf Baechle  2005-07-14  1085
     f77be1ef David Howells 2008-11-14 @1086		v->uid = filp->f_cred->fsuid;
     f77be1ef David Howells 2008-11-14 @1087  		v->gid = filp->f_cred->fsgid;
     794c686a Ralf Baechle  2006-04-05  1088
     794c686a Ralf Baechle  2006-04-05  1089		v->cwd[0] = 0;
     794c686a Ralf Baechle  2006-04-05  1090 	 	ret = getcwd(v->cwd, VPE_PATH_MAX);

When examining the code to see what v->uid and v->gid were used for I
discovered that the only users in the kernel are vpe_getuid and
vpe_getgid, and that vpe_getuid and vpe_getgid are never called.

So instead of proposing a conversion to use kuid_t and kgid_t instead
of unsigned int/int as I normally would let's just kill this dead code
so no one has to worry about it further.

Deng-Cheng Zhu said:

This is a good catch. vpe_get[u|g]id was originally used by KSPD which
has been removed.

Cc: Ralf Baechle <ralf@linux-mips.org>
Cc: linux-mips@linux-mips.org
Reviewed-by: Deng-Cheng Zhu <dengcheng.zhu@imgtec.com>
Signed-off-by: "Eric W. Biederman" <ebiederm@xmission.com>