ASoC: cq93vc: duplicated callback function goes to component
A cleanup removed a couple of members from struct snd_soc_codec_driver
after changing codec drivers to no longer use them, but one codec
was missed in the process, giving a build error:

sound/soc/codecs/cq93vc.c:134:2: error: unknown field 'controls' specified in initializer
  .controls = cq93vc_snd_controls,

This moves the members from the cq93vc codec driver to its component driver
just like the other codecs already had.

Fixes: 22f2d6b2a097 ("ASoC: remove codec duplicated callback function")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mark Brown <broonie@kernel.org>