c6x: include: asm: Kbuild: Add generic serial.h
Or it will cause building break with allmodconfig:

    CC [M]  drivers/tty/serial/8250/8250_core.o
  drivers/tty/serial/8250/8250_core.c:102:24: fatal error: asm/serial.h: No such file or directory

Signed-off-by: Chen Gang <gang.chen.5i5j@gmail.com>
Signed-off-by: Mark Salter <msalter@redhat.com>