Revert "ext4: fix to check return value of freeze_bdev() in ext4_shutdown()"
This reverts commit ffa06deebfa71158a03fa6332e6a088abfae4b54.

The patch was taken from mainline where freeze_bdev() has a different
return type, causing the following warning/error:

    ../fs/ext4/ioctl.c:541:7: error: incompatible pointer to integer
    conversion
    assigning to 'int' from 'struct super_block *' [-Wint-conversion]
      541 |                 ret = freeze_bdev(sb->s_bdev);
          |                     ^ ~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make[3]: *** [../scripts/Makefile.build:364: fs/ext4/ioctl.o] Error 1
    make[2]: *** [../scripts/Makefile.build:678: fs/ext4] Error 2
    make[2]: *** Waiting for unfinished jobs....

Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>