Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 2bd1ef7ce46555f2029eafd416593829d653f8d7.

Commit 2bd1ef7ce465 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 2bd1ef7ce465 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>