CAIF: fix tty->warned build error
After commit 49be71fc3bda ("TTY: do not warn about setting
speed via SPD_*"), we are seeing a build error when DEBUG_FS is
enabled:
drivers/net/caif/caif_serial.c: In function 'update_tty_status':
drivers/net/caif/caif_serial.c:94:11: error: 'struct tty_struct' has no member named 'warned'

Fix the error by removing the reference to the variable as it was
not set in the last decade (as documented in the changelog of the
commit above).

Signed-off-by: Jiri Slaby <jslaby@suse.cz>
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Sjur Braendeland <sjur.brandeland@stericsson.com>
Cc: netdev@vger.kernel.org
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>