ARM: mach-imx: Fix selection of ARCH_MXC
Since commit 28c91f1b(ARM: imx: enable multi-platform build),
ARCH_MXC is selected by the following logic:

config ARCH_MXC
        def_bool y if ARCH_MULTI_V4_V5 || ARCH_MULTI_V6_V7

, which causes build error on vexpress_defconfig:

arch/arm/mach-imx/hotplug.c:49: undefined reference to `imx_enable_cpu'
arch/arm/mach-imx/platsmp.c:57: undefined reference to `imx_set_cpu_jump'
arch/arm/mach-imx/platsmp.c:58: undefined reference to `imx_enable_cpu'

Make ARCH_MXC a user selectable option, so that it does not get built
by default on other defconfigs that select ARCH_MULTI_V4_V5 or ARCH_MULTI_V6_V7.

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>