Staging: most: MOST and MOSTCORE should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "dma_free_coherent" [drivers/staging/most/mostcore/mostcore.ko] undefined!
    ERROR: "dma_alloc_coherent" [drivers/staging/most/mostcore/mostcore.ko] undefined!

As all MOST sub drivers use DMA functionality, add a dependency on
HAS_DMA to MOSTCORE, and to MOST, which selects MOSTCORE.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Christian Gromm <christian.gromm@microchip.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>