Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit 27a109bd4ea180cc20be363ff9dd448a93b060e4, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer