tty/amiserial: Add missing argument for tty_unlock()
commit 83592fe1d9ea2dede692d719d7bf0451c5fbb65d ("tty_lock: Localise the lock")
missed that e7537091673d05e9510a4397f0351e4c034a3032 ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>