Revert "arm64: Add support ARCH_SUPPORTS_INT128"
This reverts commit 70c2f8be03fe623540a527efe0c7806e24558814.

The original patch and UBSAN+KASAN enabled causes Linux to fail to link
with:

lib/built-in.o: In function `get_signed_val':
lib/ubsan.c:93: undefined reference to `__ashlti3'
lib/ubsan.c:93: undefined reference to `__ashrti3'

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>